name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *" # 每天18:00触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          username: ${{ github.repository_owner }}
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY).git HEAD:main
