name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *" #每天18:00触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install -g github-profile-3d-contrib
      - name: Generate 3D Contribution Graph
        run: github-profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "generated"
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/GitHub-Profile-3D-Contrib.git HEAD:main
          fi
